import { describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { runCreateTidegate } from "./cli.ts";

async function runCli(
  argv: string[],
  { cwd, env = {} }: { cwd?: string; env?: Record<string, string | undefined> } = {},
) {
  const stdout: string[] = [];
  const stderr: string[] = [];
  const exitCode = await runCreateTidegate(argv, {
    cwd,
    env,
    fetchImpl: async () => {
      throw new Error("unexpected fetch");
    },
    generateSecret: () => "tgs_test_secret",
    stderr: (line) => stderr.push(line),
    stdout: (line) => stdout.push(line),
  });

  return { exitCode, stderr, stdout };
}

async function createNextProject(): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), "create-tidegate-cli-"));
  await writeFile(
    join(dir, "package.json"),
    `${JSON.stringify({ name: "acme-backend", dependencies: { next: "16.2.6" } })}\n`,
  );
  await mkdir(join(dir, "app"), { recursive: true });

  return dir;
}

describe("runCreateTidegate", () => {
  test("--help prints usage and exits 0", async () => {
    const cli = await runCli(["--help"]);

    expect(cli.exitCode).toBe(0);
    expect(cli.stdout.join("\n")).toContain("create-tidegate doctor");
    expect(cli.stdout.join("\n")).toContain(
      "generated by the Tidegate agent",
    );
  });

  test("unknown command exits 2 with usage on stderr", async () => {
    const cli = await runCli(["frobnicate"]);

    expect(cli.exitCode).toBe(2);
    expect(cli.stderr.join("\n")).toContain("Usage:");
  });

  test("unknown option exits 2", async () => {
    const cli = await runCli(["init", "--frobnicate", "x"]);

    expect(cli.exitCode).toBe(2);
    expect(cli.stderr.join("\n")).toContain("Unknown option --frobnicate.");
  });

  test("init positionals exit 2", async () => {
    const cli = await runCli(["init", "extra"]);

    expect(cli.exitCode).toBe(2);
  });

  test("options without the init subcommand run init, as the usage advertises", async () => {
    const project = await createNextProject();
    const outer = await mkdtemp(join(tmpdir(), "create-tidegate-outer-"));

    try {
      const cli = await runCli(["--dir", project], { cwd: outer });

      expect(cli.exitCode).toBe(0);
      expect(cli.stdout.join("\n")).toContain("Tidegate integration scaffolded");
      expect(
        await readFile(join(project, "tidegate/actions.ts"), "utf8"),
      ).toContain("defineTidegateActions");
    } finally {
      await rm(project, { force: true, recursive: true });
      await rm(outer, { force: true, recursive: true });
    }
  });

  test("inline option values keep everything after the first equals sign", async () => {
    const project = await createNextProject();

    try {
      const cli = await runCli([`--dir=${project}`, "--catalog-id=acme=books"], {
        cwd: "/",
      });

      expect(cli.exitCode).toBe(0);
      expect(
        await readFile(join(project, "app/api/action-catalog/route.ts"), "utf8"),
      ).toContain('catalogId: "acme=books"');
    } finally {
      await rm(project, { force: true, recursive: true });
    }
  });

  test("init summary lists catalog id, environment block, and install step", async () => {
    const project = await createNextProject();

    try {
      const cli = await runCli(["init"], { cwd: project });
      const output = cli.stdout.join("\n");

      expect(cli.exitCode).toBe(0);
      expect(output).toContain("catalog id: acme-backend");
      expect(output).toContain("Environment:");
      expect(output).toContain(".env.local created with a generated TIDEGATE_ACTION_BRIDGE_SECRET");
      expect(output).toContain("npm add @tidegate/sdk zod");
      expect(output).toContain("does not appear to be covered by .gitignore");
      expect(output).toContain("--secret <TIDEGATE_ACTION_BRIDGE_SECRET from .env.local>");
      expect(output).toContain("interactions are generated for you, not written by hand");
    } finally {
      await rm(project, { force: true, recursive: true });
    }
  });

  test("empty --catalog-id exits 2", async () => {
    const cli = await runCli(["init", "--catalog-id", " "]);

    expect(cli.exitCode).toBe(2);
    expect(cli.stderr.join("\n")).toContain("--catalog-id cannot be empty");
  });

  test("boolean options reject inline values", async () => {
    const cli = await runCli([
      "doctor",
      "--catalog-url",
      "http://127.0.0.1:1/api/action-catalog",
      "--json=false",
    ]);

    expect(cli.exitCode).toBe(2);
    expect(cli.stderr.join("\n")).toContain("--json takes no value.");
  });

  test("inline values may start with dashes", async () => {
    const project = await createNextProject();

    try {
      const cli = await runCli([`--dir=${project}`, "--catalog-id=--weird"], {
        cwd: "/",
      });

      expect(cli.exitCode).toBe(0);
      expect(
        await readFile(join(project, "app/api/action-catalog/route.ts"), "utf8"),
      ).toContain('catalogId: "--weird"');
    } finally {
      await rm(project, { force: true, recursive: true });
    }
  });

  test("init outside a package exits 1 with guidance on stderr", async () => {
    const dir = await mkdtemp(join(tmpdir(), "create-tidegate-cli-empty-"));

    try {
      const cli = await runCli(["init"], { cwd: dir });

      expect(cli.exitCode).toBe(1);
      expect(cli.stderr.join("\n")).toContain("No package.json found.");
      expect(cli.stdout).toEqual([]);
    } finally {
      await rm(dir, { force: true, recursive: true });
    }
  });

  test("doctor without a catalog URL exits 2 and names the env fallback", async () => {
    const cli = await runCli(["doctor"]);

    expect(cli.exitCode).toBe(2);
    expect(cli.stderr.join("\n")).toContain("TIDEGATE_ACTION_CATALOG_URL");
  });

  test("doctor --e2e without API credentials exits 2", async () => {
    const cli = await runCli([
      "doctor",
      "--catalog-url",
      "http://127.0.0.1:1/api/action-catalog",
      "--e2e",
    ]);

    expect(cli.exitCode).toBe(2);
    expect(cli.stderr.join("\n")).toContain("--e2e needs the Tidegate API");
  });

  test("doctor rejects an invalid visibility", async () => {
    const cli = await runCli([
      "doctor",
      "--catalog-url",
      "http://127.0.0.1:1/api/action-catalog",
      "--e2e",
      "--api-base-url",
      "http://127.0.0.1:1/api/v1",
      "--token",
      "test",
      "--visibility",
      "everyone",
    ]);

    expect(cli.exitCode).toBe(2);
    expect(cli.stderr.join("\n")).toContain('Invalid --visibility "everyone"');
  });

  test("doctor rejects a smoke interaction id outside the diagnostic namespace", async () => {
    const cli = await runCli([
      "doctor",
      "--catalog-url",
      "http://127.0.0.1:1/api/action-catalog",
      "--e2e",
      "--api-base-url",
      "http://127.0.0.1:1/api/v1",
      "--token",
      "test",
      "--interaction-id",
      "ix.production.payroll",
    ]);

    expect(cli.exitCode).toBe(2);
    expect(cli.stderr.join("\n")).toContain("diagnostic namespace");
  });
});
