import { randomUUID } from "node:crypto";

import {
  PublishInteractionResponseSchema,
  InvokeInteractionResponseSchema,
  TIDEGATE_ACTION_ALLOWED_ACTIONS_HEADER,
  TIDEGATE_ACTION_AUTH_CONTEXT_HEADER,
  TIDEGATE_ACTION_BRIDGE_SECRET_HEADER,
  TidegateActionCatalogManifestV1Schema,
  TidegateActionInvokeResponseSchema,
  type InvokeInteractionResponse,
  type TidegateActionCatalogManifestV1,
} from "@tidegate/contracts";

export type DoctorFetch = (
  input: Parameters<typeof fetch>[0],
  init?: Parameters<typeof fetch>[1],
) => Promise<Response>;

export const DOCTOR_PING_ACTION_ID = "diagnostics.ping";
export const SMOKE_INTERACTION_ID_PREFIX = "ix.diagnostics.";
export const DEFAULT_SMOKE_INTERACTION_ID = "ix.diagnostics.echo";

export type DoctorStageStatus = "pass" | "fail" | "warn" | "skip";

export type DoctorStage = {
  id: string;
  title: string;
  status: DoctorStageStatus;
  detail?: string;
};

export type DoctorVisibility = "user" | "tenant" | "organization" | "app";

export type DoctorConfig = {
  catalogUrl: string;
  actionsUrl?: string;
  bridgeSecret?: string;
  e2e?: {
    apiBaseUrl: string;
    token: string;
    interactionId: string;
    visibility: DoctorVisibility;
  };
};

export type DoctorDeps = {
  fetchImpl?: DoctorFetch;
};

export type DoctorReport = {
  ok: boolean;
  stages: DoctorStage[];
};

// Source of the ephemeral smoke interaction. It is a wiring test — real
// interactions are generated by the Tidegate agent, never authored from here.
const SMOKE_INTERACTION_SOURCE = `export default async function run(input, ctx) {
  const ping = await ctx.capabilities.diagnostics.ping({});

  return {
    echo: input.message,
    pong: ping.pong,
  };
}`;

const SMOKE_INTERACTION_INPUT_SCHEMA = {
  type: "object",
  required: ["message"],
  properties: {
    message: { type: "string" },
  },
  additionalProperties: false,
} as const;

const SMOKE_INTERACTION_OUTPUT_SCHEMA = {
  type: "object",
  required: ["echo", "pong"],
  properties: {
    echo: { type: "string" },
    pong: { type: "boolean" },
  },
  additionalProperties: false,
} as const;

export async function runTidegateDoctor(
  config: DoctorConfig,
  { fetchImpl = globalThis.fetch }: DoctorDeps = {},
): Promise<DoctorReport> {
  if (
    config.e2e !== undefined &&
    !config.e2e.interactionId.startsWith(SMOKE_INTERACTION_ID_PREFIX)
  ) {
    throw new Error(
      `The smoke interaction id must stay in the diagnostic namespace ("${SMOKE_INTERACTION_ID_PREFIX}*"); got "${config.e2e.interactionId}". Doctor archives this interaction after the check and must never touch a real one.`,
    );
  }

  const stages: DoctorStage[] = [];
  const catalog = await runCatalogStages({ config, fetchImpl, stages });

  // Fail-stop ordering: a red line in an earlier layer stops the later layers
  // (they would only add noise, and --e2e would create registry side effects
  // on top of a broken setup).
  if (hasFailure(stages)) {
    stages.push({
      id: "bridge",
      title: "Action bridge checks",
      status: "skip",
      detail: "Skipped: fix the catalog stage above first.",
    });
    pushEndToEndSkip(stages, config, "Skipped: fix the failing stage above first.");

    return report(stages);
  }

  await runBridgeStages({ catalog, config, fetchImpl, stages });

  if (hasFailure(stages)) {
    pushEndToEndSkip(stages, config, "Skipped: fix the failing stage above first.");

    return report(stages);
  }

  await runEndToEndStages({ catalog, config, fetchImpl, stages });

  return report(stages);
}

function report(stages: DoctorStage[]): DoctorReport {
  return { ok: !hasFailure(stages), stages };
}

function hasFailure(stages: DoctorStage[]): boolean {
  return stages.some((stage) => stage.status === "fail");
}

function pushEndToEndSkip(
  stages: DoctorStage[],
  config: DoctorConfig,
  detail: string,
): void {
  if (config.e2e !== undefined) {
    stages.push({
      id: "e2e",
      title: "End-to-end smoke test",
      status: "skip",
      detail,
    });
  }
}

async function runCatalogStages({
  config,
  fetchImpl,
  stages,
}: {
  config: DoctorConfig;
  fetchImpl: DoctorFetch;
  stages: DoctorStage[];
}): Promise<TidegateActionCatalogManifestV1 | undefined> {
  const id = "catalog-fetch";
  const title = "Catalog manifest is reachable";
  let response: Response;

  try {
    response = await fetchImpl(config.catalogUrl, {
      headers: { accept: "application/json" },
    });
  } catch (error) {
    stages.push({
      id,
      title,
      status: "fail",
      detail: `GET ${config.catalogUrl} failed: ${errorMessage(error)}. Is the backend running and the URL correct?`,
    });

    return undefined;
  }

  if (!response.ok) {
    stages.push({
      id,
      title,
      status: "fail",
      detail: `GET ${config.catalogUrl} returned HTTP ${response.status}. The catalog route must respond 200 with the manifest JSON.`,
    });

    return undefined;
  }

  let body: unknown;

  try {
    body = await response.json();
  } catch {
    stages.push({
      id,
      title,
      status: "fail",
      detail: `GET ${config.catalogUrl} responded HTTP ${response.status} but the body is not JSON — an auth wall, rewrite, or error page may be intercepting the route.`,
    });

    return undefined;
  }

  stages.push({ id, title, status: "pass" });

  const parsed = TidegateActionCatalogManifestV1Schema.safeParse(body);

  if (!parsed.success) {
    stages.push({
      id: "catalog-schema",
      title: "Catalog manifest matches tidegate.actionCatalog.v1",
      status: "fail",
      detail: parsed.error.issues
        .map((issue) => `${issue.path.join(".") || "(root)"}: ${issue.message}`)
        .join("; "),
    });

    return undefined;
  }

  const actionIds = Object.keys(parsed.data.actions);

  stages.push({
    id: "catalog-schema",
    title: "Catalog manifest matches tidegate.actionCatalog.v1",
    status: "pass",
    detail: `catalogId ${parsed.data.catalogId}, ${actionIds.length} action${actionIds.length === 1 ? "" : "s"}: ${actionIds.join(", ")}`,
  });

  const unscopedWrites = Object.entries(parsed.data.actions)
    .filter(
      ([, action]) => action.effects !== "read" && action.tenantScope === undefined,
    )
    .map(([actionId]) => actionId);

  if (unscopedWrites.length > 0) {
    stages.push({
      id: "catalog-governance",
      title: "Non-read actions declare a tenant scope",
      status: "warn",
      detail: `Missing tenantScope: ${unscopedWrites.join(", ")}. Without it the kernel cannot pin these actions to the caller's tenant.`,
    });
  } else {
    stages.push({
      id: "catalog-governance",
      title: "Non-read actions declare a tenant scope",
      status: "pass",
    });
  }

  return parsed.data;
}

async function runBridgeStages({
  catalog,
  config,
  fetchImpl,
  stages,
}: {
  catalog: TidegateActionCatalogManifestV1 | undefined;
  config: DoctorConfig;
  fetchImpl: DoctorFetch;
  stages: DoctorStage[];
}): Promise<void> {
  if (config.actionsUrl === undefined) {
    stages.push({
      id: "bridge",
      title: "Action bridge checks",
      status: "skip",
      detail:
        "No action endpoint configured. Set TIDEGATE_ACTION_ENDPOINT_URL or pass --actions-url to verify the bridge.",
    });

    return;
  }

  const actionsUrl = config.actionsUrl;

  stages.push(await bridgeAuthRejectStage({ actionsUrl, fetchImpl }));

  if (config.bridgeSecret === undefined) {
    stages.push({
      id: "bridge-allowlist",
      title: "Bridge enforces the interaction action allowlist",
      status: "skip",
      detail:
        "No bridge secret configured. Set TIDEGATE_ACTION_BRIDGE_SECRET or pass --secret to run authenticated bridge checks.",
    });

    return;
  }

  const bridgeSecret = config.bridgeSecret;

  stages.push(
    await bridgeAllowlistStage({ actionsUrl, bridgeSecret, fetchImpl }),
  );

  if (catalog !== undefined && !(DOCTOR_PING_ACTION_ID in catalog.actions)) {
    stages.push({
      id: "bridge-execute",
      title: `Bridge executes ${DOCTOR_PING_ACTION_ID}`,
      status: "warn",
      detail: `The catalog does not expose ${DOCTOR_PING_ACTION_ID}. Keep the scaffolded diagnostics action so doctor can execute a read-only end-to-end check.`,
    });

    return;
  }

  stages.push(
    await bridgeExecuteStage({ actionsUrl, bridgeSecret, fetchImpl }),
  );
}

async function bridgeAuthRejectStage({
  actionsUrl,
  fetchImpl,
}: {
  actionsUrl: string;
  fetchImpl: DoctorFetch;
}): Promise<DoctorStage> {
  const id = "bridge-auth-reject";
  const title = "Bridge rejects an invalid credential";

  try {
    const response = await postBridge({
      actionsUrl,
      allowedActionIds: [DOCTOR_PING_ACTION_ID],
      authContext: doctorAuthContext(),
      bridgeSecret: `invalid-${randomUUID()}`,
      fetchImpl,
    });

    if (response.status >= 200 && response.status < 300) {
      return {
        id,
        title,
        status: "fail",
        detail:
          "The action endpoint accepted an invalid bridge credential. This is a security defect: verify TIDEGATE_ACTION_BRIDGE_SECRET is configured on the backend and the route uses createTidegateActionHandler.",
      };
    }

    if (response.status !== 401) {
      return {
        id,
        title,
        status: "fail",
        detail: `Expected HTTP 401 for an invalid credential, got HTTP ${response.status}. Is ${actionsUrl} the createTidegateActionHandler route?`,
      };
    }

    // A 401 alone is not proof the Tidegate handler answered: a proxy or auth
    // wall can also 401. The handler always returns a contract-shaped body.
    const parsed = TidegateActionInvokeResponseSchema.safeParse(
      await response.json().catch(() => undefined),
    );

    if (
      !parsed.success ||
      parsed.data.status === "ok" ||
      parsed.data.error.code !== "auth_required"
    ) {
      return {
        id,
        title,
        status: "fail",
        detail:
          "Got HTTP 401, but the body is not a Tidegate auth_required rejection — a proxy or auth wall may be answering before the handler. Point --actions-url at the createTidegateActionHandler route.",
      };
    }

    return { id, title, status: "pass" };
  } catch (error) {
    return {
      id,
      title,
      status: "fail",
      detail: `POST ${actionsUrl} failed: ${errorMessage(error)}`,
    };
  }
}

async function bridgeAllowlistStage({
  actionsUrl,
  bridgeSecret,
  fetchImpl,
}: {
  actionsUrl: string;
  bridgeSecret: string;
  fetchImpl: DoctorFetch;
}): Promise<DoctorStage> {
  const id = "bridge-allowlist";
  const title = "Bridge enforces the interaction action allowlist";

  try {
    const response = await postBridge({
      actionsUrl,
      allowedActionIds: [],
      authContext: doctorAuthContext(),
      bridgeSecret,
      fetchImpl,
    });

    if (response.status === 401) {
      return {
        id,
        title,
        status: "fail",
        detail:
          "The configured bridge secret was rejected. It must match the TIDEGATE_ACTION_BRIDGE_SECRET configured on the backend.",
      };
    }

    const parsed = TidegateActionInvokeResponseSchema.safeParse(
      await response.json().catch(() => undefined),
    );

    if (
      response.status === 403 &&
      parsed.success &&
      parsed.data.status === "rejected" &&
      parsed.data.error.code === "action_not_allowed"
    ) {
      return { id, title, status: "pass" };
    }

    return {
      id,
      title,
      status: "fail",
      detail: `Expected a 403 action_not_allowed rejection for an empty allowlist, got HTTP ${response.status}.`,
    };
  } catch (error) {
    return {
      id,
      title,
      status: "fail",
      detail: `POST ${actionsUrl} failed: ${errorMessage(error)}`,
    };
  }
}

async function bridgeExecuteStage({
  actionsUrl,
  bridgeSecret,
  fetchImpl,
}: {
  actionsUrl: string;
  bridgeSecret: string;
  fetchImpl: DoctorFetch;
}): Promise<DoctorStage> {
  const id = "bridge-execute";
  const title = `Bridge executes ${DOCTOR_PING_ACTION_ID}`;

  // A per-run tenant id: diagnostics.ping echoes ctx.auth.tenantId back, which
  // mechanically proves the handler feeds server-derived auth (not request
  // input) into actions.
  const tenantId = `doctor-tenant-${randomUUID()}`;

  try {
    const response = await postBridge({
      actionsUrl,
      allowedActionIds: [DOCTOR_PING_ACTION_ID],
      authContext: doctorAuthContext(tenantId),
      bridgeSecret,
      fetchImpl,
    });

    const parsed = TidegateActionInvokeResponseSchema.safeParse(
      await response.json().catch(() => undefined),
    );

    if (!response.ok || !parsed.success) {
      return {
        id,
        title,
        status: "fail",
        detail: `HTTP ${response.status} with a body that is not a successful Tidegate action response.`,
      };
    }

    if (parsed.data.status !== "ok") {
      return {
        id,
        title,
        status: "fail",
        detail: `${parsed.data.error.code}: ${parsed.data.error.message}`,
      };
    }

    const output = isRecord(parsed.data.output) ? parsed.data.output : undefined;

    if (output === undefined || output.pong !== true) {
      return {
        id,
        title,
        status: "fail",
        detail:
          "The action executed but did not return { pong: true }. Keep the scaffolded diagnostics.ping implementation intact.",
      };
    }

    if (output.tenantId !== tenantId) {
      return {
        id,
        title,
        status: "fail",
        detail:
          "diagnostics.ping did not echo the server-derived tenant from ctx.auth. Keep the scaffolded implementation intact: this echo is what proves auth reaches actions from the verified request, not from input.",
      };
    }

    return { id, title, status: "pass" };
  } catch (error) {
    return {
      id,
      title,
      status: "fail",
      detail: `POST ${actionsUrl} failed: ${errorMessage(error)}`,
    };
  }
}

// The synthetic auth context doctor presents to the customer bridge. In
// production traffic this context is derived by the Tidegate kernel; doctor
// plays that role for diagnostics only.
function doctorAuthContext(tenantId?: string) {
  return {
    authMode: "m2m",
    subjectType: "service_account",
    subjectId: "create-tidegate-doctor",
    scopes: [],
    permissions: [],
    ...(tenantId === undefined ? {} : { tenantId }),
  };
}

async function postBridge({
  actionsUrl,
  allowedActionIds,
  authContext,
  bridgeSecret,
  fetchImpl,
}: {
  actionsUrl: string;
  allowedActionIds: string[];
  authContext: Record<string, unknown>;
  bridgeSecret: string;
  fetchImpl: DoctorFetch;
}): Promise<Response> {
  return fetchImpl(actionsUrl, {
    method: "POST",
    headers: {
      accept: "application/json",
      "content-type": "application/json",
      [TIDEGATE_ACTION_BRIDGE_SECRET_HEADER]: bridgeSecret,
      [TIDEGATE_ACTION_AUTH_CONTEXT_HEADER]: JSON.stringify(authContext),
      [TIDEGATE_ACTION_ALLOWED_ACTIONS_HEADER]: JSON.stringify(allowedActionIds),
    },
    body: JSON.stringify({
      actionId: DOCTOR_PING_ACTION_ID,
      input: {},
      invocationId: `doctor-${randomUUID()}`,
    }),
  });
}

async function runEndToEndStages({
  catalog,
  config,
  fetchImpl,
  stages,
}: {
  catalog: TidegateActionCatalogManifestV1 | undefined;
  config: DoctorConfig;
  fetchImpl: DoctorFetch;
  stages: DoctorStage[];
}): Promise<void> {
  if (config.e2e === undefined) {
    return;
  }

  const e2e = config.e2e;

  if (catalog !== undefined && !(DOCTOR_PING_ACTION_ID in catalog.actions)) {
    stages.push({
      id: "e2e",
      title: "End-to-end smoke test",
      status: "skip",
      detail: `The smoke interaction calls ${DOCTOR_PING_ACTION_ID}, which is missing from the catalog. Restore the scaffolded diagnostics action first.`,
    });

    return;
  }

  const apiBaseUrl = e2e.apiBaseUrl.replace(/\/+$/, "");
  const published = await publishSmokeInteraction({ apiBaseUrl, e2e, fetchImpl });
  stages.push(published.stage);

  if (published.result === undefined) {
    return;
  }

  stages.push(
    await invokeSmokeInteraction({
      apiBaseUrl,
      fetchImpl,
      invokePath: published.result.invokePath,
      token: e2e.token,
      version: published.result.version,
    }),
  );

  stages.push(
    await archiveSmokeInteraction({
      apiBaseUrl,
      fetchImpl,
      interactionId: published.result.interactionId,
      token: e2e.token,
    }),
  );
}

async function publishSmokeInteraction({
  apiBaseUrl,
  e2e,
  fetchImpl,
}: {
  apiBaseUrl: string;
  e2e: NonNullable<DoctorConfig["e2e"]>;
  fetchImpl: DoctorFetch;
}): Promise<{
  stage: DoctorStage;
  result?: { interactionId: string; version: string; invokePath: string };
}> {
  const id = "e2e-publish";
  const title = "Smoke interaction publishes through the trusted gate";

  const body = {
    requestedInteractionId: e2e.interactionId,
    title: "Tidegate wiring smoke test",
    description:
      "Ephemeral diagnostic interaction published by create-tidegate doctor to verify wiring. It is archived immediately after the check. Real interactions are generated by the Tidegate agent — do not use this as an authoring example.",
    source: SMOKE_INTERACTION_SOURCE,
    visibility: e2e.visibility,
    input: SMOKE_INTERACTION_INPUT_SCHEMA,
    output: SMOKE_INTERACTION_OUTPUT_SCHEMA,
    requestedAllowedActions: [
      { id: DOCTOR_PING_ACTION_ID, maxCalls: 1, timeoutMs: 5000 },
    ],
    effects: {
      declared: "read",
      riskLevel: "low",
      idempotency: "not_required",
    },
    timeout: {
      executionMs: 15_000,
      maxActionCalls: 1,
    },
    confirmation: {
      required: false,
      message: null,
    },
  };

  const response = await apiRequest({
    apiBaseUrl,
    body,
    fetchImpl,
    path: "interactions/publish",
    token: e2e.token,
  });

  if (!response.ok) {
    return {
      stage: { id, title, status: "fail", detail: response.detail },
    };
  }

  const parsed = PublishInteractionResponseSchema.safeParse(response.body);

  if (!parsed.success) {
    return {
      stage: {
        id,
        title,
        status: "fail",
        detail: `The publish API responded 2xx but the body does not match the publish contract: ${parsed.error.issues
          .map((issue) => `${issue.path.join(".") || "(root)"}: ${issue.message}`)
          .join("; ")}`,
      },
    };
  }

  if (parsed.data.interactionId !== e2e.interactionId) {
    // Never archive an id we did not ask for.
    return {
      stage: {
        id,
        title,
        status: "fail",
        detail: `The publish API returned interaction id "${parsed.data.interactionId}" instead of the requested "${e2e.interactionId}". Not invoking or archiving it.`,
      },
    };
  }

  return {
    stage: {
      id,
      title,
      status: "pass",
      detail: `${parsed.data.interactionId} v${parsed.data.version} — ephemeral diagnostic, archived after the check; real interactions are generated by the Tidegate agent.`,
    },
    result: {
      interactionId: parsed.data.interactionId,
      invokePath: parsed.data.invoke.path,
      version: parsed.data.version,
    },
  };
}

async function invokeSmokeInteraction({
  apiBaseUrl,
  fetchImpl,
  invokePath,
  token,
  version,
}: {
  apiBaseUrl: string;
  fetchImpl: DoctorFetch;
  invokePath: string;
  token: string;
  version: string;
}): Promise<DoctorStage> {
  const id = "e2e-invoke";
  const title = "Smoke interaction invokes end to end";

  const message = `tidegate-doctor-${randomUUID()}`;
  const invokeBody = {
    interactionVersion: version,
    input: { message },
    surfaceId: "create-tidegate-doctor",
    sessionId: `doctor-${randomUUID()}`,
    messageId: `msg-${randomUUID()}`,
  };
  // The publish response carries the canonical invoke route as an absolute
  // path; resolve it against the API origin instead of guessing the URL.
  const invokeUrl = new URL(invokePath, apiBaseUrl).toString();

  let response = await invokeRequest({ body: invokeBody, fetchImpl, invokeUrl, token });

  if (!response.ok) {
    return { id, title, status: "fail", detail: response.detail };
  }

  if (response.parsed.status === "confirmation_required") {
    // Round-trip contract: re-POST the identical body plus the token.
    response = await invokeRequest({
      body: {
        ...invokeBody,
        confirmationToken: response.parsed.confirmation.confirmationToken,
      },
      fetchImpl,
      invokeUrl,
      token,
    });

    if (!response.ok) {
      return { id, title, status: "fail", detail: response.detail };
    }
  }

  const parsed = response.parsed;

  if (parsed.status !== "ok") {
    const detail =
      parsed.status === "confirmation_required"
        ? "The invoke kept asking for confirmation after the confirmation round-trip."
        : `${parsed.error.code}: ${parsed.error.message}`;

    return { id, title, status: "fail", detail };
  }

  const output = isRecord(parsed.output) ? parsed.output : undefined;

  if (output === undefined || output.echo !== message || output.pong !== true) {
    return {
      id,
      title,
      status: "fail",
      detail:
        "The interaction executed but its output did not round-trip the input through diagnostics.ping.",
    };
  }

  return { id, title, status: "pass" };
}

async function invokeRequest({
  body,
  fetchImpl,
  invokeUrl,
  token,
}: {
  body: unknown;
  fetchImpl: DoctorFetch;
  invokeUrl: string;
  token: string;
}): Promise<
  | { ok: true; parsed: InvokeInteractionResponse }
  | { ok: false; detail: string }
> {
  let response: Response;

  try {
    response = await fetchImpl(invokeUrl, {
      method: "POST",
      headers: {
        accept: "application/json",
        authorization: `Bearer ${token}`,
        "content-type": "application/json",
      },
      body: JSON.stringify(body),
    });
  } catch (error) {
    return { ok: false, detail: `POST ${invokeUrl} failed: ${errorMessage(error)}.` };
  }

  const parsed = InvokeInteractionResponseSchema.safeParse(
    await response.json().catch(() => undefined),
  );

  if (!parsed.success) {
    return {
      ok: false,
      detail: `POST ${invokeUrl} returned HTTP ${response.status} with a body that does not match the invoke contract.`,
    };
  }

  return { ok: true, parsed: parsed.data };
}

async function archiveSmokeInteraction({
  apiBaseUrl,
  fetchImpl,
  interactionId,
  token,
}: {
  apiBaseUrl: string;
  fetchImpl: DoctorFetch;
  interactionId: string;
  token: string;
}): Promise<DoctorStage> {
  const id = "e2e-archive";
  const title = "Smoke interaction is archived after the check";

  const response = await apiRequest({
    apiBaseUrl,
    body: { confirmed: true },
    fetchImpl,
    path: `interactions/${encodeURIComponent(interactionId)}/archive`,
    token,
  });

  if (!response.ok) {
    return {
      id,
      title,
      status: "fail",
      detail: `${response.detail} The diagnostic interaction ${interactionId} may still be listed: archive it manually.`,
    };
  }

  return { id, title, status: "pass" };
}

async function apiRequest({
  apiBaseUrl,
  body,
  fetchImpl,
  path,
  token,
}: {
  apiBaseUrl: string;
  body: unknown;
  fetchImpl: DoctorFetch;
  path: string;
  token: string;
}): Promise<
  | { ok: true; body: unknown }
  | { ok: false; detail: string }
> {
  const url = `${apiBaseUrl}/${path}`;

  let response: Response;

  try {
    response = await fetchImpl(url, {
      method: "POST",
      headers: {
        accept: "application/json",
        authorization: `Bearer ${token}`,
        "content-type": "application/json",
      },
      body: JSON.stringify(body),
    });
  } catch (error) {
    return {
      ok: false,
      detail: `POST ${url} failed: ${errorMessage(error)}.`,
    };
  }

  const responseBody: unknown = await response.json().catch(() => undefined);

  if (!response.ok) {
    const error =
      isRecord(responseBody) && isRecord(responseBody.error)
        ? responseBody.error
        : undefined;

    return {
      ok: false,
      detail:
        error !== undefined
          ? `POST ${url} rejected (HTTP ${response.status}) ${String(error.code)}: ${String(error.message)}`
          : `POST ${url} returned HTTP ${response.status}.`,
    };
  }

  return { ok: true, body: responseBody };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
