// File contents emitted by `create-tidegate init` into a customer Next.js
// project. Templates import from "@tidegate/sdk/server" (the secret-aware
// server entrypoint) and use extensionless relative imports so they compile
// under a stock Next.js tsconfig.

export type ScaffoldLayout = {
  /** "app" or "src/app" — where App Router routes live. */
  appDir: string;
  /** "tidegate" or "src/tidegate" — sibling of the app dir. */
  actionsDir: string;
};

export function detectScaffoldLayout(hasSrcDir: boolean): ScaffoldLayout {
  return hasSrcDir
    ? { appDir: "src/app", actionsDir: "src/tidegate" }
    : { appDir: "app", actionsDir: "tidegate" };
}

export function actionsModuleTemplate(): string {
  return `import { z } from "zod";
import {
  TidegateActionHandlerError,
  defineTidegateActions,
  tidegateAction,
} from "@tidegate/sdk/server";

// Your Tidegate action catalog: the small set of backend domain operations
// Tidegate is allowed to call. You expose actions and approve publications;
// the interactions that orchestrate these actions are generated by the
// Tidegate agent, not written by hand.
export const actions = defineTidegateActions({
  diagnostics: {
    // Read-only, side-effect-free action used by \`create-tidegate doctor\`
    // to prove that Tidegate can reach and execute actions on this backend.
    // Keep it: it is the wiring smoke test, not an authoring example. The
    // tenant echo lets doctor prove auth reaches actions from the verified
    // request headers (ctx.auth), never from input.
    ping: tidegateAction({
      description:
        "Health check used by Tidegate diagnostics. Read-only, no side effects; echoes the server-derived tenant.",
      input: z.object({}).strict(),
      returns: z.object({
        pong: z.literal(true),
        respondedAt: z.string().min(1),
        tenantId: z.string().min(1).nullable(),
      }),
      effects: "read",
      async execute(_input, ctx) {
        return {
          pong: true as const,
          respondedAt: new Date().toISOString(),
          tenantId: ctx.auth.tenantId ?? null,
        };
      },
    }),
  },
  example: {
    // Example action: duplicate it, rename it to your first real domain
    // operation, adapt schema/permissions/audit, then delete this one.
    saveNote: tidegateAction({
      description:
        "Save a note for the authenticated tenant (replace with a real domain operation).",
      input: z.object({
        noteId: z.string().min(1),
        text: z.string().min(1).max(2000),
      }),
      returns: z.object({
        noteId: z.string().min(1),
        savedAt: z.string().min(1),
      }),
      effects: "write",
      requiredPermissions: ["notes:write"],
      tenantScope: { fromAuth: "tenantId" },
      audit: { redactPaths: ["/input/text"] },
      async execute(input, ctx) {
        // Tenant and identity always come from ctx.auth (derived server-side
        // by Tidegate) — never from the generated input.
        const tenantId = ctx.auth.tenantId;

        if (!tenantId) {
          throw new TidegateActionHandlerError(
            "auth_required",
            "This action requires a tenant-scoped credential.",
            401,
          );
        }

        // Call your real business function here, keeping domain authorization
        // inside it, e.g.:
        // await saveNoteForTenant({ tenantId, noteId: input.noteId, text: input.text });
        return { noteId: input.noteId, savedAt: new Date().toISOString() };
      },
    }),
  },
});
`;
}

export function actionsRouteTemplate(): string {
  return `import { createTidegateActionHandler } from "@tidegate/sdk/server";
import { actions } from "../../../tidegate/actions";

// Protected, executable Tidegate surface: the Tidegate Execution Kernel calls
// this endpoint through the server-side action bridge. Authentication uses
// TIDEGATE_ACTION_BRIDGE_SECRET (compared in constant time); auth context and
// the per-interaction action allowlist arrive in server-derived headers and
// are never taken from the request body.
export const POST = createTidegateActionHandler(actions);
`;
}

export function catalogRouteTemplate(catalogId: string): string {
  return `import { createTidegateActionCatalogManifest } from "@tidegate/sdk/server";
import { actions } from "../../../tidegate/actions";

// Non-executable catalog manifest: Tidegate reads it to generate the typed
// ctx.capabilities client for the agent. It carries schemas and policies,
// never code — the real actions execute only through POST /api/actions.
// It is intentionally public metadata; if your deployment must not enumerate
// its action surface, put this route behind your own auth.
const manifest = createTidegateActionCatalogManifest(actions, {
  catalogId: ${JSON.stringify(catalogId)},
});

export function GET() {
  return Response.json(manifest);
}
`;
}

export const ENV_BRIDGE_SECRET_KEY = "TIDEGATE_ACTION_BRIDGE_SECRET";
export const ENV_API_KEY_KEY = "TIDEGATE_API_KEY";

export function envBlockTemplate(bridgeSecret: string): string {
  return `# Tidegate (added by create-tidegate)
# Shared credential Tidegate presents when calling POST /api/actions. Register
# the same value in the Tidegate console; rotate it in both places together.
${ENV_BRIDGE_SECRET_KEY}=${bridgeSecret}
# API key for invoking published interactions from this backend. Create it in
# the Tidegate console, then uncomment.
# ${ENV_API_KEY_KEY}=
`;
}
