import { z } from "zod";
import {
  TidegateActionHandlerError,
  defineTidegateActions,
  tidegateAction,
} from "@tidegate/sdk/server";

// Your Tidegate action catalog: the small set of backend domain operations
// Tidegate is allowed to call. You expose actions and approve publications;
// the interactions that orchestrate these actions are generated by the
// Tidegate agent, not written by hand.
export const actions = defineTidegateActions({
  diagnostics: {
    // Read-only, side-effect-free action used by `create-tidegate doctor`
    // to prove that Tidegate can reach and execute actions on this backend.
    // Keep it: it is the wiring smoke test, not an authoring example. The
    // tenant echo lets doctor prove auth reaches actions from the verified
    // request headers (ctx.auth), never from input.
    ping: tidegateAction({
      description:
        "Health check used by Tidegate diagnostics. Read-only, no side effects; echoes the server-derived tenant.",
      input: z.object({}).strict(),
      returns: z.object({
        pong: z.literal(true),
        respondedAt: z.string().min(1),
        tenantId: z.string().min(1).nullable(),
      }),
      effects: "read",
      async execute(_input, ctx) {
        return {
          pong: true as const,
          respondedAt: new Date().toISOString(),
          tenantId: ctx.auth.tenantId ?? null,
        };
      },
    }),
  },
  example: {
    // Example action: duplicate it, rename it to your first real domain
    // operation, adapt schema/permissions/audit, then delete this one.
    saveNote: tidegateAction({
      description:
        "Save a note for the authenticated tenant (replace with a real domain operation).",
      input: z.object({
        noteId: z.string().min(1),
        text: z.string().min(1).max(2000),
      }),
      returns: z.object({
        noteId: z.string().min(1),
        savedAt: z.string().min(1),
      }),
      effects: "write",
      requiredPermissions: ["notes:write"],
      tenantScope: { fromAuth: "tenantId" },
      audit: { redactPaths: ["/input/text"] },
      async execute(input, ctx) {
        // Tenant and identity always come from ctx.auth (derived server-side
        // by Tidegate) — never from the generated input.
        const tenantId = ctx.auth.tenantId;

        if (!tenantId) {
          throw new TidegateActionHandlerError(
            "auth_required",
            "This action requires a tenant-scoped credential.",
            401,
          );
        }

        // Call your real business function here, keeping domain authorization
        // inside it, e.g.:
        // await saveNoteForTenant({ tenantId, noteId: input.noteId, text: input.text });
        return { noteId: input.noteId, savedAt: new Date().toISOString() };
      },
    }),
  },
});
