import {
  TidegateActionCatalogManifestV1Schema,
  type TidegateActionCatalogManifestV1,
  type JsonSchema,
} from "@tidegate/contracts";

export type GeneratedTidegateCapabilitiesClient = {
  filename: "tidegate-capabilities.generated.ts";
  source: string;
};

type CapabilityTreeNode = {
  actionId?: string;
  children: Map<string, CapabilityTreeNode>;
};

export const TIDEGATE_CAPABILITIES_GENERATED_FILENAME =
  "tidegate-capabilities.generated.ts";
const IDENTIFIER_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export function generateTidegateCapabilitiesClient(
  manifest: TidegateActionCatalogManifestV1,
): GeneratedTidegateCapabilitiesClient {
  const parsed = TidegateActionCatalogManifestV1Schema.parse(manifest);
  const actionEntries = Object.entries(parsed.actions).sort(([left], [right]) =>
    left.localeCompare(right),
  );
  const tree = buildCapabilityTree(actionEntries.map(([actionId]) => actionId));
  const source = [
    "/* eslint-disable */",
    "// Generated by Tidegate. Do not edit by hand.",
    "",
    "export type TidegateActionMap = {",
    ...actionEntries.flatMap(([actionId, action]) => [
      `  ${quoted(actionId)}: {`,
      `    input: ${jsonSchemaToType(action.input, 2)};`,
      `    output: ${jsonSchemaToType(action.output, 2)};`,
      `    effects: ${JSON.stringify(action.effects)};`,
      "  };",
    ]),
    "};",
    "",
    "export type TidegateActionId = keyof TidegateActionMap;",
    "",
    "export type TidegateRuntimeActionCaller = {",
    "  call(actionId: string, input: unknown): Promise<unknown>;",
    "};",
    "",
    "export type TidegateGeneratedAuthContext = {",
    "  organizationId?: string;",
    "  organizationExternalId?: string;",
    "  subjectId?: string;",
    "  subjectType?: \"user\" | \"service_account\" | \"api_key\" | \"agent\";",
    "  subjectExternalId?: string;",
    "  credentialId?: string;",
    "  credentialType?: \"api_key\" | \"m2m_access_token\" | \"oauth_access_token\" | \"session\" | \"local_dev\";",
    "  scopes: string[];",
    "  authorization?: {",
    "    permissions: string[];",
    "    resourceGrants: Array<{",
    "      resourceType: string;",
    "      resourceId: string;",
    "      permissions: string[];",
    "    }>;",
    "  };",
    "  userId?: string;",
    "  workosUserId?: string;",
    "  orgId?: string;",
    "  tenantId?: string;",
    "  salonId?: string;",
    "  clientId?: string;",
    "  machineClientId?: string;",
    "  permissions: string[];",
    "  authMode: \"api-key\" | \"delegated\" | \"user\" | \"m2m\" | \"local-dev\";",
    "};",
    "",
    "export type TidegateGeneratedAbortSignal = {",
    "  readonly aborted: boolean;",
    "  readonly reason?: unknown;",
    "  throwIfAborted?(): void;",
    "};",
    "",
    "export type TidegateGeneratedRuntimeContext = {",
    "  auth: TidegateGeneratedAuthContext;",
    "  signal: TidegateGeneratedAbortSignal;",
    "};",
    "",
    `export type TidegateCapabilities = ${emitCapabilityTreeType(tree, 0)};`,
    "",
    "export type TidegateGeneratedInteractionContext = TidegateGeneratedRuntimeContext & {",
    "  capabilities: TidegateCapabilities;",
    "};",
    "",
    "export function createTidegateCapabilities(",
    "  actions: TidegateRuntimeActionCaller,",
    "): TidegateCapabilities {",
    `  return ${emitCapabilityTreeValue(tree, 1)};`,
    "}",
    "",
    "export function withTidegateCapabilities<",
    "  TContext extends TidegateGeneratedRuntimeContext & { actions: TidegateRuntimeActionCaller },",
    ">(ctx: TContext): Omit<TContext, \"actions\"> & { capabilities: TidegateCapabilities } {",
    "  const { actions, ...publicContext } = ctx;",
    "",
    "  return Object.assign(publicContext, {",
    "    capabilities: createTidegateCapabilities(actions),",
    "  });",
    "}",
    "",
  ].join("\n");

  return {
    filename: TIDEGATE_CAPABILITIES_GENERATED_FILENAME,
    source,
  };
}

export function jsonSchemaToTypeScriptType(schema: JsonSchema): string {
  return jsonSchemaToType(schema, 0);
}

function buildCapabilityTree(actionIds: string[]): CapabilityTreeNode {
  const root = createTreeNode();

  for (const actionId of actionIds) {
    const segments = actionId.split(".");

    if (segments.some((segment) => segment.length === 0)) {
      throw new Error(`Action id "${actionId}" contains an empty segment.`);
    }

    let current = root;

    for (const segment of segments) {
      if (current.actionId !== undefined) {
        throw new Error(
          `Action id "${actionId}" conflicts with "${current.actionId}".`,
        );
      }

      let child = current.children.get(segment);

      if (!child) {
        child = createTreeNode();
        current.children.set(segment, child);
      }

      current = child;
    }

    if (current.children.size > 0) {
      throw new Error(`Action id "${actionId}" conflicts with a namespace.`);
    }

    current.actionId = actionId;
  }

  return root;
}

function createTreeNode(): CapabilityTreeNode {
  return {
    children: new Map(),
  };
}

function emitCapabilityTreeType(
  node: CapabilityTreeNode,
  depth: number,
): string {
  const entries = [...node.children.entries()].sort(([left], [right]) =>
    left.localeCompare(right),
  );

  if (entries.length === 0) {
    return "Record<string, never>";
  }

  const indent = indentation(depth);
  const childIndent = indentation(depth + 1);
  const lines = entries.map(([segment, child]) => {
    if (child.actionId !== undefined) {
      return `${childIndent}${propertyName(segment)}(input: TidegateActionMap[${quoted(
        child.actionId,
      )}]["input"]): Promise<TidegateActionMap[${quoted(child.actionId)}]["output"]>;`;
    }

    return `${childIndent}${propertyName(segment)}: ${emitCapabilityTreeType(
      child,
      depth + 1,
    )};`;
  });

  return `{\n${lines.join("\n")}\n${indent}}`;
}

function emitCapabilityTreeValue(
  node: CapabilityTreeNode,
  depth: number,
): string {
  const entries = [...node.children.entries()].sort(([left], [right]) =>
    left.localeCompare(right),
  );
  const indent = indentation(depth);
  const childIndent = indentation(depth + 1);
  const lines = entries.map(([segment, child]) => {
    if (child.actionId !== undefined) {
      return `${childIndent}${propertyName(segment)}: (input) => actions.call(${quoted(
        child.actionId,
      )}, input) as Promise<TidegateActionMap[${quoted(child.actionId)}]["output"]>,`;
    }

    return `${childIndent}${propertyName(segment)}: ${emitCapabilityTreeValue(
      child,
      depth + 1,
    )},`;
  });

  return `{\n${lines.join("\n")}\n${indent}}`;
}

function jsonSchemaToType(schema: JsonSchema, depth: number): string {
  if (!isRecord(schema)) {
    return "unknown";
  }

  if (typeof schema.$ref === "string") {
    throw new Error(
      `JSON Schema $ref is not supported by Tidegate capability codegen: ${schema.$ref}`,
    );
  }

  if (Array.isArray(schema.enum)) {
    const values = schema.enum.map((value) => literalType(value));
    return values.length > 0 ? values.join(" | ") : "never";
  }

  if ("const" in schema) {
    return literalType(schema.const);
  }

  if (Array.isArray(schema.anyOf)) {
    return unionFromSchemas(schema.anyOf, depth);
  }

  if (Array.isArray(schema.oneOf)) {
    return unionFromSchemas(schema.oneOf, depth);
  }

  if (Array.isArray(schema.allOf)) {
    const parts = schema.allOf.map((item) =>
      jsonSchemaToType(item as JsonSchema, depth),
    );
    return parts.length > 0 ? parts.join(" & ") : "unknown";
  }

  const schemaType = schema.type;

  if (Array.isArray(schemaType)) {
    return schemaType
      .filter((item): item is string => typeof item === "string")
      .map((item) => jsonSchemaTypeToTypeScript(item, schema, depth))
      .join(" | ");
  }

  if (typeof schemaType === "string") {
    return jsonSchemaTypeToTypeScript(schemaType, schema, depth);
  }

  if (Object.keys(schema).length > 0) {
    throw new Error(
      "Unsupported JSON Schema shape for Tidegate capability codegen. Use inline schemas with type, enum, const, anyOf, oneOf, or allOf.",
    );
  }

  return "unknown";
}

function jsonSchemaTypeToTypeScript(
  schemaType: string,
  schema: JsonSchema,
  depth: number,
): string {
  switch (schemaType) {
    case "object":
      return objectSchemaToType(schema, depth);
    case "array":
      return `${arrayItemType(jsonSchemaToType(arrayItemSchema(schema), depth))}[]`;
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      return "unknown";
  }
}

function objectSchemaToType(schema: JsonSchema, depth: number): string {
  const properties = isRecord(schema.properties) ? schema.properties : {};
  const required = new Set(
    Array.isArray(schema.required)
      ? schema.required.filter((item): item is string => typeof item === "string")
      : [],
  );
  const entries = Object.entries(properties).sort(([left], [right]) =>
    left.localeCompare(right),
  );

  if (entries.length === 0) {
    return recordTypeForAdditionalProperties(schema, depth);
  }

  if (isRecord(schema.additionalProperties)) {
    throw new Error(
      "JSON Schema objects with both named properties and schema-valued additionalProperties are not supported by Tidegate capability codegen.",
    );
  }

  const indent = indentation(depth);
  const childIndent = indentation(depth + 1);
  const propertyLines = entries.map(([key, value]) => {
    const optional = required.has(key) ? "" : "?";

    return `${childIndent}${propertyName(key)}${optional}: ${jsonSchemaToType(
      value as JsonSchema,
      depth + 1,
    )};`;
  });

  if (schema.additionalProperties !== false) {
    propertyLines.push(`${childIndent}[key: string]: unknown;`);
  }

  return `{\n${propertyLines.join("\n")}\n${indent}}`;
}

function recordTypeForAdditionalProperties(
  schema: JsonSchema,
  depth: number,
): string {
  if (schema.additionalProperties === false) {
    return "Record<string, never>";
  }

  if (isRecord(schema.additionalProperties)) {
    return `Record<string, ${jsonSchemaToType(
      schema.additionalProperties,
      depth,
    )}>`;
  }

  return "Record<string, unknown>";
}

function arrayItemSchema(schema: JsonSchema): JsonSchema {
  return isRecord(schema.items) ? schema.items : {};
}

function arrayItemType(type: string): string {
  return type.includes(" | ") || type.includes(" & ") ? `(${type})` : type;
}

function unionFromSchemas(items: unknown[], depth: number): string {
  const parts = items.map((item) => jsonSchemaToType(item as JsonSchema, depth));

  return parts.length > 0 ? parts.join(" | ") : "unknown";
}

function literalType(value: unknown): string {
  if (typeof value === "string") {
    return JSON.stringify(value);
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (value === null) {
    return "null";
  }

  return "unknown";
}

function propertyName(value: string): string {
  return IDENTIFIER_PATTERN.test(value) ? value : quoted(value);
}

function quoted(value: string): string {
  return JSON.stringify(value);
}

function indentation(depth: number): string {
  return "  ".repeat(depth);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
